(function(){
"use strict";
const S="https://nmmetzityubqbrbpibee.supabase.co",K="sb_publishable_o8bXQ5puE8EUgEn_c_qM6A_7OOxZIsX",db=window.supabase.createClient(S,K);
let ownedEvents=[],historyEvents=[],ownerId=null;
const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");
function past(e){return typeof window.isPastEvent==="function"?window.isPastEvent(e.event_date,e.event_time,e.timezone):new Date(`${e.event_date}T${e.event_time||"23:59"}`).getTime()<Date.now()}
async function load(){const {data:{session}}=await db.auth.getSession();if(!session?.user)return;ownerId=session.user.id;const {data,error}=await db.from("events").select("id,name,user_id,event_date,event_time,timezone,attendance_confirmed");if(error){console.error(error);return}historyEvents=data||[];ownedEvents=historyEvents.filter(e=>e.user_id===ownerId&&past(e))}
function getCardEventId(card){const id=card.dataset.eventId||card.getAttribute("data-event-id");if(id&&/^\d+$/.test(id))return Number(id);const edit=card.querySelector(".edit-button");const m=edit?.getAttribute("onclick")?.match(/openEditModal\((\d+)\)/);return m?Number(m[1]):null}
async function getWarnings(rows,currentId){const ids=[...new Set((rows||[]).map(r=>r.user_id).filter(Boolean))];if(!ids.length)return{};const pe=historyEvents.filter(e=>e.id!==currentId&&past(e)).sort((a,b)=>new Date(`${b.event_date}T${b.event_time||"23:59"}`).getTime()-new Date(`${a.event_date}T${a.event_time||"23:59"}`).getTime()),eid=pe.map(e=>e.id);if(!eid.length)return{};const {data:hist,error}=await db.from("event_participants").select("event_id,user_id,attended").in("user_id",ids).in("event_id",eid);if(error)return{};const out={};for(const id of ids){const list=(hist||[]).filter(r=>r.user_id===id).sort((a,b)=>eid.indexOf(a.event_id)-eid.indexOf(b.event_id)).slice(0,7),abs=list.filter(r=>historyEvents.find(e=>e.id===r.event_id)?.attendance_confirmed===true&&r.attended===false).length;if(abs>=3)out[id]={icon:"🚨",abs,total:list.length};else if(abs>=2)out[id]={icon:"⚠️",abs,total:list.length}}return out}
async function openAttendance(e){const {data:rows,error}=await db.from("event_participants").select("user_id,player_name,attended").eq("event_id",e.id).order("player_name");if(error){alert("No se pudieron cargar los participantes.");return}const warnings=await getWarnings(rows,e.id),confirmed=e.attendance_confirmed===true,m=document.createElement("div");m.className="attendance-modal";m.innerHTML=`<div class="attendance-panel"><h2>${confirmed?"✏️ Editar inasistencias":"👥 Confirmar inasistencias"}</h2><div class="attendance-subtitle">${esc(e.name)}<br><strong>Marca únicamente a quienes NO asistieron.</strong><br><span style="font-size:12px;color:#888">Los que queden sin marcar se consideran asistentes.</span></div>${rows?.length?rows.map(r=>{const w=warnings[r.user_id];return `<label class="attendance-row"><input type="checkbox" data-user-id="${esc(r.user_id)}" ${confirmed&&r.attended===false?"checked":""}><span style="flex:1">${esc(r.player_name||"Jugador")}${w?`<small style="display:block;margin-top:4px;color:${w.icon==='🚨'?'#ff9b9b':'#f0cf79'}">${w.icon} ${w.abs} inasistencias en sus últimas ${w.total} participaciones</small>`:""}</span></label>`}).join(""):"<div style='color:#aaa;padding:10px'>No hubo participantes.</div>"}<div class="attendance-actions"><button type="button" class="attendance-cancel">Cancelar</button><button type="button" class="attendance-save">${confirmed?"Guardar cambios":"Confirmar inasistencias"}</button></div></div>`;document.body.appendChild(m);const panel=m.querySelector(".attendance-panel");panel.addEventListener("click",ev=>ev.stopPropagation());m.querySelector(".attendance-cancel").onclick=ev=>{ev.preventDefault();ev.stopPropagation();m.remove()};m.querySelector(".attendance-save").onclick=async ev=>{ev.preventDefault();ev.stopPropagation();const b=ev.currentTarget;b.disabled=true;b.textContent="Guardando...";for(const i of m.querySelectorAll("input[data-user-id]")){const {error}=await db.from("event_participants").update({attended:!i.checked}).eq("event_id",e.id).eq("user_id",i.dataset.userId);if(error){alert("No se pudo guardar la asistencia.");b.disabled=false;b.textContent=confirmed?"Guardar cambios":"Confirmar inasistencias";return}}const result=await db.from("events").update({attendance_confirmed:true}).eq("id",e.id);if(result.error){alert("No se pudo confirmar la actividad.");b.disabled=false;b.textContent=confirmed?"Guardar cambios":"Confirmar inasistencias";return}e.attendance_confirmed=true;closeAttendanceAndRefresh(e)} }
function closeAttendanceAndRefresh(e){const modal=document.querySelector(".attendance-modal");if(modal)modal.remove();const button=document.querySelector(`.attendance-button[data-event-id="${e.id}"]`);if(button)button.textContent="✏️ Editar inasistencias"}
function renderButton(e){const list=document.getElementById("eventsList");if(!list)return;const card=[...list.querySelectorAll(".event-card")].find(c=>getCardEventId(c)===Number(e.id));if(!card)return;const actions=card.querySelector(".event-actions");if(!actions)return;let b=actions.querySelector(`.attendance-button[data-event-id="${e.id}"]`);if(!b){b=document.createElement("button");b.type="button";b.className="attendance-button";b.dataset.eventId=String(e.id);actions.appendChild(b)}b.textContent=e.attendance_confirmed?"✏️ Editar inasistencias":"👥 Confirmar inasistencias";b.onclick=ev=>{ev.preventDefault();ev.stopPropagation();ev.stopImmediatePropagation();openAttendance(e)};b.onmousedown=ev=>ev.stopPropagation()}
function inject(){const list=document.getElementById("eventsList");if(!list||!ownerId)return;ownedEvents.forEach(e=>renderButton(e))}
async function start(){await load();inject();const list=document.getElementById("eventsList");if(list)new MutationObserver(()=>setTimeout(inject,100)).observe(list,{childList:true,subtree:true});setInterval(inject,1000)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start);else start();
})();