(function(){
"use strict";
const S="https://nmmetzityubqbrbpibee.supabase.co",K="sb_publishable_o8bXQ5puE8EUgEn_c_qM6A_7OOxZIsX",db=window.supabase.createClient(S,K);
let ownedEvents=[],historyEvents=[],ownerId=null;
const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");
function past(e){return typeof window.isPastEvent==="function"?window.isPastEvent(e.event_date,e.event_time,e.timezone):new Date(`${e.event_date}T${e.event_time||"23:59"}`).getTime()<Date.now()}
function getCardEventId(card){const id=card.dataset.eventId||card.getAttribute("data-event-id");if(id&&/^\d+$/.test(id))return Number(id);const edit=card.querySelector(".edit-button");const m=edit?.getAttribute("onclick")?.match(/openEditModal\((\d+)\)/);return m?Number(m[1]):null}
async function load(){const appUser=window.currentUser;const {data:{session}}=await db.auth.getSession();const user=appUser||session?.user;if(!user?.id)return false;ownerId=user.id;const {data,error}=await db.from("events").select("id,name,user_id,event_date,event_time,timezone,status,cancellation_reason,not_realized_reason,cancelled_at,attendance_confirmed");if(error){console.error("Error cargando eventos para asistencia:",error);return false}historyEvents=data||[];ownedEvents=historyEvents.filter(e=>String(e.user_id)===String(ownerId));inject();return true}
async function getWarnings(rows,currentId){const ids=[...new Set((rows||[]).map(r=>r.user_id).filter(Boolean))];if(!ids.length)return{};const pe=historyEvents.filter(e=>e.id!==currentId&&past(e)&&e.status!=="cancelled"&&e.status!=="not_realized").sort((a,b)=>new Date(`${b.event_date}T${b.event_time||"23:59"}`).getTime()-new Date(`${a.event_date}T${a.event_time||"23:59"}`).getTime()),eid=pe.map(e=>e.id);if(!eid.length)return{};const {data:hist,error}=await db.from("event_participants").select("event_id,user_id,attended").in("user_id",ids).in("event_id",eid);if(error)return{};const out={};for(const id of ids){const list=(hist||[]).filter(r=>r.user_id===id).sort((a,b)=>eid.indexOf(a.event_id)-eid.indexOf(b.event_id)).slice(0,7),abs=list.filter(r=>historyEvents.find(e=>e.id===r.event_id)?.attendance_confirmed===true&&r.attended===false).length;if(abs>=3)out[id]={icon:"🚨",abs,total:list.length};else if(abs>=2)out[id]={icon:"⚠️",abs,total:list.length}}return out}
async function openAttendance(e){const {data:rows,error}=await db.from("event_participants").select("user_id,player_name,attended").eq("event_id",e.id).order("player_name");if(error){alert("No se pudieron cargar los participantes.");return}const warnings=await getWarnings(rows,e.id),confirmed=e.attendance_confirmed===true,m=document.createElement("div");m.className="attendance-modal";m.innerHTML=`<div class="attendance-panel"><h2>${confirmed?"✏️ Editar inasistencias":"👥 Confirmar inasistencias"}</h2><div class="attendance-subtitle">${esc(e.name)}<br><strong>Marca únicamente a quienes NO asistieron.</strong><br><span style="font-size:12px;color:#888">Los que queden sin marcar se consideran asistentes.</span></div>${rows?.length?rows.map(r=>{const w=warnings[r.user_id];return `<label class="attendance-row"><input type="checkbox" data-user-id="${esc(r.user_id)}" ${confirmed&&r.attended===false?"checked":""}><span style="flex:1">${esc(r.player_name||"Jugador")}${w?`<small style="display:block;margin-top:4px;color:${w.icon==='🚨'?'#ff9b9b':'#f0cf79'}">${w.icon} ${w.abs} inasistencias en sus últimas ${w.total} participaciones</small>`:""}</span></label>`}).join(""):"<div style='color:#aaa;padding:10px'>No hubo participantes.</div>"}<div class="attendance-actions"><button type="button" class="attendance-cancel">Cancelar</button><button type="button" class="attendance-save">${confirmed?"Guardar cambios":"Confirmar inasistencias"}</button></div></div>`;document.body.appendChild(m);const panel=m.querySelector(".attendance-panel");panel.addEventListener("click",ev=>ev.stopPropagation());m.querySelector(".attendance-cancel").onclick=ev=>{ev.preventDefault();ev.stopPropagation();m.remove()};m.querySelector(".attendance-save").onclick=async ev=>{ev.preventDefault();ev.stopPropagation();const b=ev.currentTarget;b.disabled=true;b.textContent="Guardando...";for(const i of m.querySelectorAll("input[data-user-id]")){const {error}=await db.from("event_participants").update({attended:!i.checked}).eq("event_id",e.id).eq("user_id",i.dataset.userId);if(error){alert("No se pudo guardar la asistencia.");b.disabled=false;b.textContent=confirmed?"Guardar cambios":"Confirmar inasistencias";return}}const result=await db.from("events").update({attendance_confirmed:true}).eq("id",e.id);if(result.error){alert("No se pudo confirmar la actividad.");b.disabled=false;b.textContent=confirmed?"Guardar cambios":"Confirmar inasistencias";return}e.attendance_confirmed=true;closeAttendanceAndRefresh(e)}}
function ensureActions(card){let actions=card.querySelector(".event-actions");if(actions)return actions;actions=document.createElement("div");actions.className="event-actions";actions.style.cssText="display:flex;flex-wrap:wrap;gap:8px;align-items:center;margin-top:10px";card.appendChild(actions);return actions}
async function markNotRealized(e){if(e.status==="not_realized"||e.status==="cancelled")return;if(!past(e)||e.attendance_confirmed===true)return;const reason=prompt("Motivo de por qué no se realizó (opcional):","");if(reason===null)return;if(!confirm(`¿Marcar "${e.name}" como \"No realizada\"?\n\nLa actividad se conservará en el Histórico y no contará como realizada ni generará inasistencias.`))return;const {data,error}=await db.functions.invoke("not-realized-event",{body:{event_id:e.id,reason:reason.trim()||null}});if(error||data?.error){console.error("No realizada:",error||data?.error);alert("No se pudo marcar la actividad como no realizada.");return}e.status="not_realized";e.not_realized_reason=reason.trim()||null;renderButton(e);if(typeof window.loadEvents==="function")await window.loadEvents()}
async function cancelEvent(e){if(e.status==="cancelled"||e.status==="not_realized")return;const reason=prompt("Motivo de la cancelación (opcional):","");if(reason===null)return;if(!confirm(`¿Cancelar la actividad "${e.name}"?\n\nLa actividad permanecerá en el Histórico como cancelada.`))return;const now=new Date().toISOString();const {error}=await db.from("events").update({status:"cancelled",cancellation_reason:reason.trim()||null,cancelled_at:now}).eq("id",e.id).eq("user_id",ownerId);if(error){console.error(error);alert("No se pudo cancelar la actividad.");return}e.status="cancelled";e.cancellation_reason=reason.trim()||null;e.cancelled_at=now;renderButton(e);try{const r=await db.functions.invoke("send-push",{body:{type:"event_cancelled",event_id:e.id}});if(r.error)console.error("Error enviando notificación de cancelación:",r.error)}catch(err){console.error(err)}try{const r=await db.functions.invoke("discord-event",{body:{action:"web_cancel_event",event_id:e.id,reason:e.cancellation_reason}});if(r.error)console.error("Error actualizando Discord:",r.error)}catch(err){console.error("Error actualizando Discord:",err)}if(typeof window.loadEvents==="function")await window.loadEvents()}
function renderButton(e){const list=document.getElementById("eventsList");if(!list)return;const card=[...list.querySelectorAll(".event-card")].find(c=>getCardEventId(c)===Number(e.id));if(!card)return;const actions=ensureActions(card);let status=card.querySelector(`.event-cancelled-label[data-event-id="${e.id}"]`),nr=card.querySelector(`.event-not-realized-label[data-event-id="${e.id}"]`);let b=actions.querySelector(`.attendance-button[data-event-id="${e.id}"]`),cb=actions.querySelector(`.cancel-event-button[data-event-id="${e.id}"]`),nb=actions.querySelector(`.not-realized-button[data-event-id="${e.id}"]`);
if(e.status==="cancelled"){if(b)b.remove();if(cb)cb.remove();if(nb)nb.remove();if(nr)nr.remove();if(!status){status=document.createElement("div");status.className="event-cancelled-label";status.dataset.eventId=String(e.id);status.style.cssText="margin-top:0;padding:7px 10px;border-radius:6px;background:#4a2222;border:1px solid #7a3a3a;color:#ffb0b0;font-weight:bold;text-align:center";actions.appendChild(status)}status.textContent="❌ Actividad cancelada";if(e.cancellation_reason){const r=document.createElement("div");r.style.cssText="font-size:12px;font-weight:normal;color:#d8a9a9;margin-top:4px";r.textContent=e.cancellation_reason;status.replaceChildren(document.createTextNode("❌ Actividad cancelada"),r)}return}
if(e.status==="not_realized"){if(b)b.remove();if(cb)cb.remove();if(status)status.remove();if(!nr){nr=document.createElement("div");nr.className="event-not-realized-label";nr.dataset.eventId=String(e.id);nr.style.cssText="margin-top:0;padding:7px 10px;border-radius:6px;background:#3a3a22;border:1px solid #6a6a3a;color:#e0df9a;font-weight:bold;text-align:center";actions.appendChild(nr)}nr.replaceChildren(document.createTextNode("🚫 Actividad \"No realizada\""));if(e.not_realized_reason){const r=document.createElement("div");r.style.cssText="font-size:12px;font-weight:normal;color:#d8d8a9;margin-top:4px";r.textContent=e.not_realized_reason;nr.appendChild(r)}return}
if(status)status.remove();if(nr)nr.remove();
if(past(e)){
 if(cb)cb.remove();
 if(e.attendance_confirmed===true){if(nb)nb.remove()}else{
  if(!nb){nb=document.createElement("button");nb.type="button";nb.className="not-realized-button";nb.dataset.eventId=String(e.id);nb.style.cssText="margin-top:0;background:#66662f;color:#fff;border:none;padding:7px 12px;border-radius:5px;cursor:pointer;font-weight:bold";actions.appendChild(nb)}
  nb.textContent="🚫 Marcar \"No realizada\"";
 }
 if(!b){b=document.createElement("button");b.type="button";b.className="attendance-button";b.dataset.eventId=String(e.id);actions.appendChild(b)}
 b.textContent=e.attendance_confirmed?"✏️ Editar inasistencias":"👥 Confirmar inasistencias";
}else{
 if(b)b.remove();if(nb)nb.remove();
 if(!cb){cb=document.createElement("button");cb.type="button";cb.className="cancel-event-button";cb.dataset.eventId=String(e.id);cb.style.cssText="margin-top:0;background:#8f3030;color:#fff;border:none;padding:7px 12px;border-radius:5px;cursor:pointer;font-weight:bold";actions.appendChild(cb)}
 cb.textContent="❌ Cancelar actividad";
}}
function inject(){const list=document.getElementById("eventsList");if(!list||!ownerId)return;ownedEvents.forEach(e=>renderButton(e))}
async function start(){await load();db.auth.onAuthStateChange((event,session)=>{if(session?.user){ownerId=session.user.id;setTimeout(load,50)}});[300,1000,2500,5000].forEach(ms=>setTimeout(()=>{if(!ownerId&&window.currentUser)load();else if(ownerId)inject()},ms));document.addEventListener("click",ev=>{const cb=ev.target.closest?.(".cancel-event-button");if(cb){ev.preventDefault();ev.stopPropagation();ev.stopImmediatePropagation();const id=Number(cb.dataset.eventId),e=ownedEvents.find(x=>Number(x.id)===id);if(e)cancelEvent(e);return}const nb=ev.target.closest?.(".not-realized-button");if(nb){ev.preventDefault();ev.stopPropagation();ev.stopImmediatePropagation();const id=Number(nb.dataset.eventId),e=ownedEvents.find(x=>Number(x.id)===id);if(e)markNotRealized(e);return}const b=ev.target.closest?.(".attendance-button");if(!b)return;const id=Number(b.dataset.eventId);const e=ownedEvents.find(x=>Number(x.id)===id)||historyEvents.find(x=>Number(x.id)===id);if(!e)return;ev.preventDefault();ev.stopPropagation();ev.stopImmediatePropagation();openAttendance(e)},true);inject();const list=document.getElementById("eventsList");if(list)new MutationObserver(()=>setTimeout(inject,50)).observe(list,{childList:true,subtree:true});setInterval(()=>{if(ownerId)inject()},1500);const fix=document.createElement("script");fix.src="history-fix.js?v=4";document.body.appendChild(fix);const rt=document.createElement("script");rt.src="realtime.js?v=1";document.body.appendChild(rt)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start);else start();
})();