(function(){
"use strict";
const S="https://nmmetzityubqbrbpibee.supabase.co",K="sb_publishable_o8bXQ5puE8EUgEn_c_qM6A_7OOxZIsX";
const db=window.supabase.createClient(S,K);
const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");
function getId(card){const id=card.dataset.eventId||card.getAttribute("data-event-id");if(id&&/^\d+$/.test(id))return Number(id);const b=card.querySelector(".edit-button");const m=b?.getAttribute("onclick")?.match(/openEditModal\((\d+)\)/);return m?Number(m[1]):null}
function paintCancelled(card,event){if(!card||card.querySelector(".cancelled-badge"))return;const badge=document.createElement("div");badge.className="cancelled-badge";badge.innerHTML="❌ <strong>Actividad cancelada</strong>";badge.style.cssText="margin:10px 0;padding:9px 12px;border-radius:6px;background:#3a2020;border:1px solid #7a3838;color:#ffb0b0;font-size:13px";const body=card.querySelector(".event-description")||card.querySelector(".event-info")||card.firstElementChild;body?.after(badge);card.querySelectorAll("button").forEach(b=>{if(!b.classList.contains("edit-button")&&!b.classList.contains("delete-button")&&!b.classList.contains("attendance-button"))b.disabled=true});card.style.opacity=".72"}
function addCancelButton(card,event){if(event.status==="cancelled"){paintCancelled(card,event);return}if(event.user_id!==window.currentUser?.id)return;if(card.querySelector(".cancel-event-button"))return;const actions=card.querySelector(".event-actions");if(!actions)return;const b=document.createElement("button");b.type="button";b.className="cancel-event-button";b.textContent="❌ Cancelar actividad";b.style.cssText="margin-top:10px;background:#8f3030;color:#fff;border:none;padding:7px 12px;border-radius:5px;cursor:pointer;font-weight:bold";b.onclick=async ev=>{ev.preventDefault();ev.stopPropagation();const reason=prompt("Motivo de la cancelación (opcional):","");if(reason===null)return;b.disabled=true;b.textContent="Cancelando...";try{const {data,error}=await db.functions.invoke("cancel-event",{body:{event_id:event.id,reason:reason.trim()}});if(error||data?.error)throw error||new Error(data.error);await window.loadEvents();}catch(e){console.error("❌ Error cancelando actividad:",e);alert("No se pudo cancelar la actividad.");b.disabled=false;b.textContent="❌ Cancelar actividad"}};actions.appendChild(b)}
function inject(){const list=document.getElementById("eventsList");if(!list||!Array.isArray(window.events))return;document.querySelectorAll("#eventsList .event-card").forEach(card=>{const id=getId(card);const event=window.events.find(e=>Number(e.id)===id);if(event)addCancelButton(card,event)})}
const observer=new MutationObserver(()=>setTimeout(inject,30));const list=document.getElementById("eventsList");if(list)observer.observe(list,{childList:true,subtree:true});window.addEventListener("load",()=>setTimeout(inject,500));setInterval(inject,1200);inject();
})();